# permissions for end users to view secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-viewer-role
rules:
- apiGroups:
  - core.codius.org
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.codius.org
  resources:
  - secrets/status
  verbs:
  - get
